name: Check Paths

on:
  push:
  pull_request:

jobs:
  checkpaths:
    name: Check Paths
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check templates.json
        run: pwsh ci/CheckInvalidTemplatePaths.ps1 templates.json
