name: Check Paths

on:
  push:
  pull_request:

jobs:
  checkpaths:
    name: Check Paths
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Check templates.json
        run: pwsh ci/CheckInvalidTemplatePaths.ps1 templates.json
