name: Check Dates

on:
  pull_request:

jobs:
  check_dates:
    name: Check Dates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get Changed Files
        id: files
        uses: tj-actions/changed-files@7dee1b0c1557f278e5c7dc244927139d78c0e22a # v47.0.4
        with:
          separator: ","

      - name: Check Dates
        shell: pwsh
        run: |
          $files = "${{ steps.files.outputs.all_changed_files }}".Split(',')
          $nowDate = Get-Date -Format "yyyy-MM-dd"
          ci/CheckInvalidDates.ps1 $files $nowDate
