name: Check Paths

on:
  push:
  pull_request:

jobs:
  checkpaths:
    name: Check Paths
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check templates.json
        run: pwsh ci/CheckInvalidTemplatePaths.ps1 templates.json
